language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
cache: bundler
before_install:
- gem install bundler:2.2.16

script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure:
  app: 
  on:
    repo: github/Yardsourcing/yardsourcing-frontend
  run: rails db:migrate
