language: ruby
rbenv:
- 2.5.3
env:
  global:
    secure: 
addons:
  postgresql: 9.6
cache: bundler
before_install:
- gem install bundler:2.2.16
- nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: MreFoOzcHxol45MsuoAdXbs8AmHA1yY6M5rgp96vAvvYTYnNLUg8TLwOBAD3eWZPsDChSwA8f0X6O/O5dfONlVIa2tdFQBRa845bl2IHS3Jn1Ef8uvBE6eqdrCruF+jyujJkL6ATy73MetCzMrsD8AT3/DOf8rhwybvrLoKvU+K43R1iIX3xGrC+Ytd4h0pdhB4f0njIbtC3MZYQ1+XdNKXiVxzTd7HRGJlCHG7dTa/r2SWOckektRBPy4fBuqfkVsuaoQ7lrde1MB4L8+ER3GuLNHtBnddOi1h1ZhjWXc2tv+A+qvO97YvCBqPVi8717iImsVReRJHaLY6AOhku5fLFotQG3et1s9inbADc1OaT0pVK7WPQc9NDeuWWiQWKnrHRbx2Hgs93gopQo/BqOVuiSzAeO2+BHzlq35N5x6MbVNY55Hwj1E97zSdnmg535VSpW26mfGWZrrleu23TaDzurwfLqUs5CE1+qJdZJS1/MwYzGn//yM6PqX4NaUfJ0J1vhPTSJ/4m/kRgw41JswVqgK2ltDLPKT5UGl+O85dC6NC7H3xZQzQ9cbXWRdTuFRPpfMnivHr9HofLLJetFN0p5wFi0MUMgFJKvwN6+wGRWE22F+mBZn3Kr7BSOiX05++441CSzUsNmLFw4FqfRmEHRiCKLCEdNq79g0fYHdY=
  app: secure-harbor-78053
  on:
    repo: jordanfbeck0528/sweater_weather
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
